spring.application.name=demo6

server.port=${PORT:8080}
#spring.mongodb.uri=mongodb+srv://akram:f0a9i8z7@clusterakram.6ha4hl8.mongodb.net/ecommerce
spring.mongodb.uri=${MONGO_URI:mongodb+srv://akram:f0a9i8z7@clusterakram.6ha4hl8.mongodb.net/ecommerce}
